server:
  port: 8080

logging:
  level:
    root: INFO
    com.nby.agent: DEBUG
    org.springframework.web: INFO
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /data/app/logs/sf-ai-agent.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: sf-ai-agent
  prometheus:
    metrics:
      export:
        enabled: true
